name: model1 
on: [push] 
jobs:  
  run:    
  runs-on: [ubuntu-latest]
  container: docker://dvcorg/cml-py3:latest
  steps:      
    - uses: actions/checkout@v2       
    - name: cml_run       
    env:          
      repo_toek: ${{ secrets.GITHUB_TOKEN }}
    run:
        pip install -r requirements.txt
        train.py
        
        echo "model metrics"
        cat metrics.txt
        
